// '#2c3e50'
const GAME_PARAMETERS = {
  SNAKE_PART_SIZE: 15,
  BOARD_COLOR: '#E8F7EE',
  SNAKE_STROKE_COLOR: '#304D6D',
  SNAKE_FILL_COLOR: '#545E75',
  SNAKE_LINE_WIDTH: 1,
  SNAKE_STEP_SIZE: 1,
  SNAKE_STEP_DELAY: 100,
}

export { GAME_PARAMETERS };