// '#2c3e50'
const GAME_PARAMETERS = {
  SNAKE_PART_SIZE: 20,
  SNAKE_STEP_SPEED_DIVIDER: 8,
  BOARD_COLOR: '#E8F7EE',
  SNAKE_STROKE_COLOR: '#304D6D',
  SNAKE_FILL_COLOR: '#545E75',
  SNAKE_LINE_WIDTH: 1,
  SNAKE_STEP_SIZE: 20,
  SNAKE_FEED_SIZE: 20
};

export { GAME_PARAMETERS };
